export const ADMISSION_CREATE_SUCCESS = 'ADMISSION_CREATE_SUCCESS';
export const ADMISSION_CREATE_FAIL = 'ADMISSION_CREATE_FAIL';
export const ADMISSION_CREATE_RESET = 'ADMISSION_CREATE_RESET';

export const ADMISSION_UPDATE_SUCCESS = 'ADMISSION_UPDATE_SUCCESS';
export const ADMISSION_UPDATE_FAIL = 'ADMISSION_UPDATE_FAIL';
export const ADMISSION_UPDATE_RESET = 'ADMISSION_UPDATE_RESET';

export const ADMISSION_DELETE_SUCCESS = 'ADMISSION_DELETE_SUCCESS';
export const ADMISSION_DELETE_FAIL = 'ADMISSION_DELETE_FAIL';

export const ADMISSION_ALL_SUCCESS = 'ADMISSION_ALL_SUCCESS';
export const ADMISSION_ALL_FAIL = 'ADMISSION_ALL_FAIL';

export const ADMISSION_DETAIL_SUCCESS = 'ADMISSION_DETAIL_SUCCESS';
export const ADMISSION_DETAIL_FAIL = 'ADMISSION_DETAIL_FAIL';
export const ADMISSION_DETAIL_RESET = 'ADMISSION_DETAIL_RESET';

export const MY_ADMISSIONS_SUCCESS = 'MY_ADMISSIONS_SUCCESS';
export const MY_ADMISSIONS_FAIL = 'MY_ADMISSIONS_FAIL';
export const MY_ADMISSIONS_RESET = 'MY_BOOKS_RESET';

export const ADMISSION_BACKGROUND_SUCCESS = 'ADMISSION_BACKGROUND_SUCCESS';
export const ADMISSION_BACKGROUND_FAIL = 'ADMISSION_BACKGROUND_FAIL';

export const ADMISSION_COMMENT_SUCCESS = 'ADMISSION_COMMENT_SUCCESS';
export const ADMISSION_COMMENT_FAIL = 'ADMISSION_COMMENT_FAIL';
export const ADMISSION_COMMENT_RESET = 'ADMISSION_COMMENT_RESET';

export const ADMISSION_PERCENTAGE_SUCCESS = 'ADMISSION_PERCENTAGE_SUCCESS';
export const ADMISSION_PERCENTAGE_FAIL = 'ADMISSION_PERCENTAGE_FAIL';
export const ADMISSION_PERCENTAGE_RESET = 'ADMISSION_PERCENTAGE_RESET';