export const COLLEGE_LIST_SUCCESS = 'COLLEGE_LIST_SUCCESS';
export const COLLEGE_LIST_FAIL = 'COLLEGE_LIST_FAIL';

export const COLLEGE_DETAILS_SUCCESS = 'COLLEGE_DETAILS_SUCCESS';
export const COLLEGE_DETAILS_FAIL = 'COLLEGE_DETAILS_FAIL';

export const COLLEGE_BY_NAME_SUCCESS = 'COLLEGE_BY_NAME_SUCCESS';
export const COLLEGE_BY_NAME_FAIL = 'COLLEGE_BY_NAME_FAIL';