export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';
export const POST_CREATE_RESET = 'POST_CREATE_RESET';

export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_ALL_SUCCESS = 'POST_ALL_SUCCESS';
export const POST_ALL_FAIL = 'POST_ALL_FAIL';

export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_FAIL = 'POST_DETAIL_FAIL';
export const POST_DETAIL_RESET = 'POST_DETAIL_RESET';

export const MY_POSTS_SUCCESS = 'MY_POSTS_SUCCESS';
export const MY_POSTS_FAIL = 'MY_POSTS_FAIL';
export const MY_POSTS_RESET = 'MY_BOOKS_RESET';

export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL';
export const POST_COMMENT_RESET = 'POST_COMMENT_RESET';