export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT = 'LOGOUT';

export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_FAIL = 'USER_CHANGE_PASSWORD_FAIL';

export const USER_BACKGROUND_SUCCESS = 'USER_BACKGROUND_SUCCESS';
export const USER_BACKGROUND_FAIL = 'USER_BACKGROUND_FAIL';
export const USER_BACKGROUND_RESET = 'USER_BACKGROUND_RESET'

export const USER_UPDATE_BACKGROUND_SUCCESS = 'USER_UPDATE_BACKGROUND_SUCCESS';
export const USER_UPDATE_BACKGROUND_FAIL = 'USER_UPDATE_BACKGROUND_FAIL';
export const USER_UPDATE_BACKGROUND_RESET = 'USER_UPDATE_BACKGROUND_RESET';